export const data = [
  "chocalate",
  "choclate biscuits",
  "cherries",
  "ice",
  "apple",
  "almonds",
  "almondoil",
  "icecream",
  "icecream biscuits",
  "cheese",
  "cheeseburgur",
  "almondsbiscuits",
  "banana",
  "basket",
  "ballon",
  "iced Tea",
  "tomato",
  "tomato ketchups",
  "tomato soup",
  "tomato salad",
];
